---
- name: PREPARE GUID
  hosts: all
  roles:
    - 1_PREPARE_GUID

- name: PRE CHECKS
  hosts: nodes,nfs
  roles:
    - 2_PRE_CHECKS

- name: INSTALL REQUIRED PACKAGES
  hosts: localhost
  roles:
    - 3_INSTALL_REQUIRED_PACKAGES

- name: INITIATE HOSTS FILE
  hosts: localhost
  roles:
    - 4_INITIATE_HOSTS_FILE

- name: CHECK ANSIBLE PREREQUISITES
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

- name: EXECUTE ANSIBLE DEPLOYER
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: POST CLUSTER DEPLOY CHECKS
  hosts: all,localhost
  roles:
    - 5_POST_CLUSTER_DEPLOY

- name: SMOKE TEST
  hosts: localhost
  roles:
    - 5_POST_CLUSTER_DEPLOY
