---
- name: INSTALL REQUIRED PACKAGES
  hosts: localhost
  tasks:
    - name: CHECK REQUIRED PACKAGES
      yum:
        name:
          - atomic-openshift-utils
          - atomic-openshift-clients
        state: present
