---
- name: CHECK DOCKER INSTALL AND CONFIG
  hosts: nodes
  tasks:
    - name: docker restart
      shell: systemctl status docker | grep Active

- name: CHECK NFS SHARED VOLUMES ON HOSTS
  hosts: nfs
  tasks:
    - name: CHECK NFS SHARED VOLUMES
      shell: exportfs
