---
- name: SMOKE TEST
  script: nodejs_mongo_smoke_test.sh

- name: SMOKE TEST SUCEEDED MESSAGE
  debug:
    msg: ">>>>>>> [ SMOKE TEST SUCCEEDED ] <<<<<<<<<"

- name: SMOKE TEST CLEAN UP
  script: oc delete project smoke-test-nodejs
  script: oc project default
