---
- name: SMOKE TEST
  script: nodejs_mongo_smoke_test.sh

- name: CHECK IF POD IS ALIVE
  script: curl -o /dev/null -s -w "%{http_code}" http://nodejs-mongo-persistent-smoke-test-nodejs.apps.${GUID}.example.opentlc.com
  register: result
  until: result.status == 200
  retries: 120
  delay: 2

- name: SMOKE TEST SUCEEDED MESSAGE
  debug:
    msg: ">>>>>>> [ SMOKE TEST SUCCEEDED ] <<<<<<<<<"
  when: result == 200

- name: SMOKE TEST CLEAN UP
  script: oc delete project smoke-test-nodejs
