---
- name: SMOKE TEST
  script: nodejs_mongo_smoke_test.sh

- name: CHECK IF POD IS ALIVE
  uri:
    url: "nodejs-mongo-persistent-smoke-test-nodejs.apps.${GUID}.example.opentlc.com"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 120
  delay: 2

- name: SMOKE TEST SUCEEDED MESSAGE
  debug:
    msg: ">>>>>>> [ SMOKE TEST SUCCEEDED ] <<<<<<<<<"
  when: result.status == 200

- name: SMOKE TEST CLEAN UP
  script: oc delete project smoke-test-nodejs
