---
- name: COPY THE CONFIG FILE FROM MASTERS
  fetch:
    src: /root/.kube/config
    dest: /root/.kube/config
    flat: yes
    tags: check-role
  when: "'masters' in group_names"

- name: CHECK system:admin ROLE
  shell: oc whoami
  when: "inventory_hostname == 'localhost'"

- name: CHECK ALL NODES
  shell: oc get nodes
  when: "inventory_hostname == 'localhost'"

- name: CREATE ALL PV FOLDERS
  file:
    dest: "/srv/nfs/user-vols/pv{{ item }}"
    state: directory
    group: nfsnobody
    owner: nfsnobody
    mode: 0777
  with_sequence: start=1 end=50
  when: "'nfs' in group_names"

- name: CONFIGURE THE EXPORTS
  shell: echo "/srv/nfs/user-vols/pv{{ item }} *(rw,root_squash)" >> /etc/exports.d/openshift-uservols.exports
  with_sequence: start=1 end=50
  when: "'nfs' in group_names"

- name: CREATE 25 PVs 5 gigs
  script: create_pvs_5gigs.sh

- name: CREATE 25 PVs 10 gigs
  script: create_pvs_10Gigs.sh

- name: CREATE ALL PVs FROM DEFINITIONS FILES
  shell: cat /root/pvs/* | oc create -f -

- name: FIX NFS PERSISTENCE
  shell: "{{ item }}"
  with_items:
    - "docker pull registry.access.redhat.com/openshift3/ose-recycler:latest"
    - "docker tag registry.access.redhat.com/openshift3/ose-recycler:latest registry.access.redhat.com/openshift3/ose-recycler:v3.9.30"
  when: "'nodes' in group_names"
