---
- name: CREATE PVS
  script:  create_pvs.sh

- name: CREATE 25 PVs 5 gigs
  script:  create_pvs_5gigs.sh

- name: CREATE 25 PVs 10 gigs
  script: create_pvs_10Gigs.sh

- name: CREATE ALL PVs FROM DEFINITIONS FILES
  shell: cat /root/pvs/* | oc create -f -

- name:  FIX NFS PV RECYCLING - Pulling ose recycler image
  shell: docker pull registry.access.redhat.com/openshift3/ose-recycler:latest

- name:  FIX NFS PV RECYCLING - Tagging ose recycler image
  shell: docker tag registry.access.redhat.com/openshift3/ose-recycler:latest registry.access.redhat.com/openshift3/ose-recycler:v3.9.30
