---
- name: >>> PREPATE GUID AND ENV VARIABLES FOR ALL HOSTS
  hosts: all
  tasks:
    - name: ALL GUID ENV VARIABLES
      shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc

- name: >>> CHECK DOCKER INSTALL AND CONFIG
  hosts: nodes
  tasks:
    - name: docker restart
      shell: systemctl status docker | grep Active

- name: >>> CHECK NFS SHARED VOLUMES ON HOSTS
  hosts: nfs
  tasks:
    - name: CHECK NFS SHARED VOLUMES
      shell: exportfs

- name: >>> INSTALL PACKAGES AND CONFIG AUTH
  hosts: localhost
  tasks:
    - name: CHECK REQUIRED PACKAGES
      yum:
        name:
          - atomic-openshift-utils
          - atomic-openshift-clients
        state: present

- name: Generate Inventory Hosts File
  hosts: localhost
  tasks:
    - name: Generate Inventory script
      script: ./scripts/generate_inventory.sh

- name: Execute the openshift-ansible prerequisites
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

- name: Execute the openshift-ansible Deployer
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: Verify OpenShift Cluster
  hosts: masters[0]
  tasks:
    - name: copy the .kube directory from master1 to your bastion
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/config
        flat: yes

- name: Post installation configuration
  hosts: localhost
  tasks:
    - name: make sure you are system:dmin
      shell: oc whoami | grep system:admin
    - name: grant user1 to administrator privilege
      shell: oc adm policy add-cluster-role-to-user cluster-admin user1

- name: Create PVs for Users
  hosts: nfs
  tasks:
    - name: Create PVs
      script: ./config/infra/pvs/create_pvs.sh

- name: Create 25 definitions files for PVs 5G size
  hosts: localhost
  tasks:
    - name: Create 25 definitions files 5G size
      script: ./config/infra/pvs/create_pvs_5gigs.sh

- name: Create 25 definitions files for PVs 10G size
  hosts: localhost
  tasks:
    - name: Create 25 definitions files 10G size
      script: ./config/infra/pvs/create_pvs_10gigs.sh

- name: Create all PVs from definitions files
  hosts: localhost
  tasks:
    - name: Create 25 definitions files 5G size
      shell: cat /root/pvs/* | oc create -f -

- name: Fix NFS Persistent Volume Recycling
  hosts: nodes
  tasks:
    - name: Pulling ose recycler image
      shell: docker pull registry.access.redhat.com/openshift3/ose-recycler:latest
    - name: Tagging ose recycler image
      shell: docker tag registry.access.redhat.com/openshift3/ose-recycler:latest registry.access.redhat.com/openshift3/ose-recycler:v3.9.30

- name: Smoke Test
  hosts: localhost
  tasks:
    - name: Smoke Test
      script: ./scripts/nodejs_mongo_app.sh

- name: CI CD workflow
  hosts: localhost
  tasks:
    - name: CI CD workflow
      script: ./scripts/cicd.sh

- name: HPA configuration on production deployment of openshift-tasks
  hosts: localhost
  tasks:
    - name: HPA configuration
      shell: oc autoscale dc/openshift-tasks --min=1 --max=5 --cpu-percent=70 -n basic-spring-boot-prod

- name: Multitenancy
  hosts: localhost
  tasks:
    - name: Multitenancy
      script: ./config/infra/setup_multitenancy.sh
