---
- name: PREPATE GUID AND ENV VARIABLES FOR ALL HOSTS
  hosts: all
  tasks:
    - name: ALL GUID ENV VARIABLES
      shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc

- name: CHECK DOCKER INSTALL AND CONFIG
  hosts: nodes
  tasks:
    - name: docker restart
      shell: systemctl status docker | grep Active

- name: CHECK NFS SHARED VOLUMES ON HOSTS
  hosts: nfs
  tasks:
    - name: CHECK NFS SHARED VOLUMES
      shell: exportfs

- name: INSTALL PACKAGES AND CONFIG AUTH
  hosts: localhost
  tasks:
    - name: CHECK REQUIRED PACKAGES
      yum:
        name:
          - atomic-openshift-utils
          - atomic-openshift-clients
        state: present

- name: INITIATE HOSTS FILE
  hosts: localhost
  tasks:
    - name: INITIATE HOSTS
      script:  /root/ocpAdvDepl/config/bin/initiateHostsTemplate.sh

- name: CHECK ANSIBLE PREREQUISITES
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

- name: EXECUTE ANSIBLE DEPLOYER
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: CHECK OPENSHIFT CLUSTER
  hosts: masters[0]
  tasks:
    - name: COPY THE .kube FOLDER FROM MASTER1 TO BASTION
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/config
        flat: yes

- name: POST INSTALL CONFIG
  hosts: localhost
  tasks:
    - name: make sure you are system:dmin
      shell: oc whoami | grep system:admin
    - name: grant user1 to administrator privilege
      shell: oc adm policy add-cluster-role-to-user cluster-admin user1

- name: CREATE PVS USERS
  hosts: nfs
  tasks:
    - name: Create PVs
      script:  /root/ocpAdvDepl/config/infra/pvs/create_pvs.sh

- name: CREATE 25 PVs 5 gigs
  hosts: localhost
  tasks:
    - name: Create 25 definitions files 5G size
      script:  /root/ocpAdvDepl/config/infra/pvs/create_pvs_5gigs.sh

- name: CREATE 25 PVs 10 gigs
  hosts: localhost
  tasks:
    - name: Create 25 definitions files 10G size
      script:  /root/ocpAdvDepl/config/infra/pvs/create_pvs_10Gigs.sh

- name: CREATE ALL PVs FROM DEFINITIONS FILES
  hosts: localhost
  tasks:
    - name: Create 25 definitions files 5G size
      shell: cat /root/pvs/* | oc create -f -

- name:  FIX NFS PV RECYCLING
  hosts: nodes
  tasks:
    - name: Pulling ose recycler image
      shell: docker pull registry.access.redhat.com/openshift3/ose-recycler:latest
    - name: Tagging ose recycler image
      shell: docker tag registry.access.redhat.com/openshift3/ose-recycler:latest registry.access.redhat.com/openshift3/ose-recycler:v3.9.30

- name: SMOKE TEST
  hosts: localhost
  tasks:
    - name: Smoke Test
      script:  /root/ocpAdvDepl/config/bin/nodejs_mongo_smoke_test.sh

- name: CI CD workflow
  hosts: localhost
  tasks:
    - name: CI CD workflow
      script:  /root/ocpAdvDepl/config/infra/setup_cicd_no_ha.sh

- name: HPA CONFIG ON PROD
  hosts: localhost
  tasks:
    - name: HPA configuration
      shell: oc autoscale dc/os-tasks --min 1 --max 10 --cpu-percent=80 -n os-tasks-${GUID}-prod

- name: MULTITENANCY SETUP
  hosts: localhost
  tasks:
    - name: MULTITENANCY SETUP
      script:  /root/ocpAdvDepl/config/infra/setup_multitenacy.sh
