---
- name: PREINSTALL AND INITIATE HOSTS FILES
  roles:
    - 1_PREPARE_GUID
    - 2_PRE_CHECKS
    - 3_INSTALL_REQUIRED_PACKAGES
    - 4_INITIATE_HOSTS_FILE

- name: CHECK ANSIBLE PREREQUISITES
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

- name: EXECUTE ANSIBLE DEPLOYER
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: CLUSTER CONFIGURATION, CREATE PVS, CICD WORKFLOW, ON BOARD NEW USERS
  roles:
    - 7_PREPARE_KUBE_FOLDER
    - 8_CREATE_CLUSTER_ADMIN
    - 9_CREATE_PVS
    - 10_SMOKE_TEST
    - 11_CICD_WORKFLOW
    - 12_HPA_CONFIG_PROD
    - 13_MULTITENANT
    - 14_ON_BOARD_NEW_USERS
